knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '%env(resolve:GOOGLE_CLIENT_ID_GOOGLE)%'
            client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET_GOOGLE)%'
            redirect_route: connect_google_check
            redirect_params: 
                service: google
        github:
            type: github
            client_id: '%env(resolve:GITHUB_CLIENT_ID)%'
            client_secret: '%env(resolve:GITHUB_CLIENT_SECRET)%'
            redirect_route: connect_github_check
            redirect_params: {}
        facebook:
            type: facebook
            client_id: '%env(resolve:FB_CLIENT_ID)%'
            client_secret: '%env(resolve:FB_CLIENT_SECRET)%'
            redirect_route: '%env(resolve:FB_CALLBACK)%' 
            redirect_params: {}
            graph_api_version: 'v2.10'
            ##redirect_route